/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define CONFIG_FLASH_BASE_ADDRESS 0x0
// #define FT6X06_USE_SIMPLE_I2C_API 0
// #define ILI9341_USE_DBI_IFACE 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_OS_CUSTOM_INCLUDE "stdint.h"
#define CONFIG_LV_DRAW_SW_ASM_CUSTOM_INCLUDE ""
#define CONFIG_LV_ASSERT_HANDLER_INCLUDE "assert.h"
#define CONFIG_LV_GLOBAL_CUSTOM_INCLUDE "lv_global.h"
#define CONFIG_LV_TXT_BREAK_CHARS " ,.;:-_)}"
#define CONFIG_LV_PROFILER_INCLUDE "lvgl/src/misc/lv_profiler_builtin.h"
// #define CONFIG_LV_CONF_SKIP 0
// #define CONFIG_LV_CONF_MINIMAL 0
// #define CONFIG_LV_COLOR_DEPTH_32 0
// #define CONFIG_LV_COLOR_DEPTH_24 0
#define CONFIG_LV_COLOR_DEPTH_16 1
// #define CONFIG_LV_COLOR_DEPTH_8 0
// #define CONFIG_LV_COLOR_DEPTH_1 0
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_USE_BUILTIN_MALLOC 1
// #define CONFIG_LV_USE_CLIB_MALLOC 0
// #define CONFIG_LV_USE_MICROPYTHON_MALLOC 0
// #define CONFIG_LV_USE_RTTHREAD_MALLOC 0
// #define CONFIG_LV_USE_CUSTOM_MALLOC 0
#define CONFIG_LV_USE_BUILTIN_STRING 1
// #define CONFIG_LV_USE_CLIB_STRING 0
// #define CONFIG_LV_USE_CUSTOM_STRING 0
#define CONFIG_LV_USE_BUILTIN_SPRINTF 1
// #define CONFIG_LV_USE_CLIB_SPRINTF 0
// #define CONFIG_LV_USE_CUSTOM_SPRINTF 0
#define CONFIG_LV_MEM_SIZE_KILOBYTES 30
#define CONFIG_LV_MEM_POOL_EXPAND_SIZE_KILOBYTES 0
#define CONFIG_LV_MEM_ADR 0x0
#define CONFIG_LV_DEF_REFR_PERIOD 33
#define CONFIG_LV_DPI_DEF 130
// #define CONFIG_LV_OS_NONE 0
// #define CONFIG_LV_OS_PTHREAD 0
#define CONFIG_LV_OS_FREERTOS 1
// #define CONFIG_LV_OS_CMSIS_RTOS2 0
// #define CONFIG_LV_OS_RTTHREAD 0
// #define CONFIG_LV_OS_WINDOWS 0
// #define CONFIG_LV_OS_MQX 0
// #define CONFIG_LV_OS_CUSTOM 0
#define CONFIG_LV_USE_OS 2
#define CONFIG_LV_USE_FREERTOS_TASK_NOTIFY 1
#define CONFIG_LV_DRAW_BUF_STRIDE_ALIGN 1
#define CONFIG_LV_DRAW_BUF_ALIGN 4
#define CONFIG_LV_DRAW_LAYER_SIMPLE_BUF_SIZE 24576
#define CONFIG_LV_DRAW_THREAD_STACK_SIZE 8192
#define CONFIG_LV_USE_DRAW_SW 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB565 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB565A8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_XRGB8888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_ARGB8888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_L8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_AL88 1
#define CONFIG_LV_DRAW_SW_SUPPORT_A8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_I1 1
#define CONFIG_LV_DRAW_SW_DRAW_UNIT_CNT 1
// #define CONFIG_LV_USE_DRAW_ARM2D_SYNC 0
// #define CONFIG_LV_USE_NATIVE_HELIUM_ASM 0
#define CONFIG_LV_DRAW_SW_COMPLEX 1
// #define CONFIG_LV_USE_DRAW_SW_COMPLEX_GRADIENTS 0
#define CONFIG_LV_DRAW_SW_SHADOW_CACHE_SIZE 0
#define CONFIG_LV_DRAW_SW_CIRCLE_CACHE_SIZE 4
#define CONFIG_LV_DRAW_SW_ASM_NONE 1
// #define CONFIG_LV_DRAW_SW_ASM_NEON 0
// #define CONFIG_LV_DRAW_SW_ASM_HELIUM 0
// #define CONFIG_LV_DRAW_SW_ASM_CUSTOM 0
#define CONFIG_LV_USE_DRAW_SW_ASM 0
// #define CONFIG_LV_USE_DRAW_VGLITE 0
// #define CONFIG_LV_USE_PXP 0
// #define CONFIG_LV_USE_DRAW_G2D 0
// #define CONFIG_LV_USE_DRAW_DAVE2D 0
// #define CONFIG_LV_USE_DRAW_SDL 0
// #define CONFIG_LV_USE_DRAW_VG_LITE 0
// #define CONFIG_LV_USE_VECTOR_GRAPHIC 0
// #define CONFIG_LV_USE_LOG 0
// #define CONFIG_LV_USE_ASSERT_NULL 0
// #define CONFIG_LV_USE_ASSERT_MALLOC 0
// #define CONFIG_LV_USE_ASSERT_STYLE 0
// #define CONFIG_LV_USE_ASSERT_MEM_INTEGRITY 0
// #define CONFIG_LV_USE_ASSERT_OBJ 0
// #define CONFIG_LV_USE_REFR_DEBUG 0
// #define CONFIG_LV_USE_LAYER_DEBUG 0
// #define CONFIG_LV_USE_PARALLEL_DRAW_DEBUG 0
// #define CONFIG_LV_ENABLE_GLOBAL_CUSTOM 0
#define CONFIG_LV_CACHE_DEF_SIZE 0
#define CONFIG_LV_IMAGE_HEADER_CACHE_DEF_CNT 0
#define CONFIG_LV_GRADIENT_MAX_STOPS 2
#define CONFIG_LV_COLOR_MIX_ROUND_OFS 128
// #define CONFIG_LV_OBJ_STYLE_CACHE 0
// #define CONFIG_LV_USE_OBJ_ID 0
// #define CONFIG_LV_USE_OBJ_PROPERTY 0
// #define CONFIG_LV_BIG_ENDIAN_SYSTEM 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE 1
// #define CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM 0
// #define CONFIG_LV_USE_FLOAT 0
// #define CONFIG_LV_USE_MATRIX 0
// #define CONFIG_LV_USE_PRIVATE_API 0
// #define CONFIG_LV_FONT_MONTSERRAT_8 0
// #define CONFIG_LV_FONT_MONTSERRAT_10 0
// #define CONFIG_LV_FONT_MONTSERRAT_12 0
#define CONFIG_LV_FONT_MONTSERRAT_14 1
#define CONFIG_LV_FONT_MONTSERRAT_16 1
// #define CONFIG_LV_FONT_MONTSERRAT_18 0
// #define CONFIG_LV_FONT_MONTSERRAT_20 0
// #define CONFIG_LV_FONT_MONTSERRAT_22 0
#define CONFIG_LV_FONT_MONTSERRAT_24 1
// #define CONFIG_LV_FONT_MONTSERRAT_26 0
// #define CONFIG_LV_FONT_MONTSERRAT_28 0
// #define CONFIG_LV_FONT_MONTSERRAT_30 0
// #define CONFIG_LV_FONT_MONTSERRAT_32 0
// #define CONFIG_LV_FONT_MONTSERRAT_34 0
// #define CONFIG_LV_FONT_MONTSERRAT_36 0
// #define CONFIG_LV_FONT_MONTSERRAT_38 0
// #define CONFIG_LV_FONT_MONTSERRAT_40 0
// #define CONFIG_LV_FONT_MONTSERRAT_42 0
// #define CONFIG_LV_FONT_MONTSERRAT_44 0
// #define CONFIG_LV_FONT_MONTSERRAT_46 0
// #define CONFIG_LV_FONT_MONTSERRAT_48 0
// #define CONFIG_LV_FONT_MONTSERRAT_28_COMPRESSED 0
// #define CONFIG_LV_FONT_DEJAVU_16_PERSIAN_HEBREW 0
// #define CONFIG_LV_FONT_SIMSUN_14_CJK 0
// #define CONFIG_LV_FONT_SIMSUN_16_CJK 0
// #define CONFIG_LV_FONT_UNSCII_8 0
// #define CONFIG_LV_FONT_UNSCII_16 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_8 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_10 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12 0
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14 1
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_18 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_24 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_30 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_32 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_34 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_36 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_38 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_40 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_42 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_44 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_46 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_48 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED 0
// #define CONFIG_LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW 0
// #define CONFIG_LV_FONT_DEFAULT_SIMSUN_14_CJK 0
// #define CONFIG_LV_FONT_DEFAULT_SIMSUN_16_CJK 0
// #define CONFIG_LV_FONT_DEFAULT_UNSCII_8 0
// #define CONFIG_LV_FONT_DEFAULT_UNSCII_16 0
// #define CONFIG_LV_FONT_FMT_TXT_LARGE 0
// #define CONFIG_LV_USE_FONT_COMPRESSED 0
#define CONFIG_LV_USE_FONT_PLACEHOLDER 1
#define CONFIG_LV_TXT_ENC_UTF8 1
// #define CONFIG_LV_TXT_ENC_ASCII 0
#define CONFIG_LV_TXT_LINE_BREAK_LONG_LEN 0
// #define CONFIG_LV_USE_BIDI 0
// #define CONFIG_LV_USE_ARABIC_PERSIAN_CHARS 0
#define CONFIG_LV_WIDGETS_HAS_DEFAULT_VALUE 1
#define CONFIG_LV_USE_ANIMIMG 1
#define CONFIG_LV_USE_ARC 1
#define CONFIG_LV_USE_BAR 1
#define CONFIG_LV_USE_BUTTON 1
#define CONFIG_LV_USE_BUTTONMATRIX 1
#define CONFIG_LV_USE_CALENDAR 1
// #define CONFIG_LV_CALENDAR_WEEK_STARTS_MONDAY 0
#define CONFIG_LV_USE_CALENDAR_HEADER_ARROW 1
#define CONFIG_LV_USE_CALENDAR_HEADER_DROPDOWN 1
// #define CONFIG_LV_USE_CALENDAR_CHINESE 0
#define CONFIG_LV_USE_CANVAS 1
#define CONFIG_LV_USE_CAROUSEL 1
#define CONFIG_LV_USE_CHART 1
#define CONFIG_LV_USE_CHECKBOX 1
#define CONFIG_LV_USE_DROPDOWN 1
#define CONFIG_LV_USE_IMAGE 1
#define CONFIG_LV_USE_IMAGEBUTTON 1
#define CONFIG_LV_USE_KEYBOARD 1
#define CONFIG_LV_USE_LABEL 1
// #define CONFIG_LV_LABEL_TEXT_SELECTION 0
// #define CONFIG_LV_LABEL_LONG_TXT_HINT 0
#define CONFIG_LV_LABEL_WAIT_CHAR_COUNT 3
#define CONFIG_LV_USE_LED 1
#define CONFIG_LV_USE_LINE 1
#define CONFIG_LV_USE_LIST 1
#define CONFIG_LV_USE_MENU 1
#define CONFIG_LV_USE_MSGBOX 1
#define CONFIG_LV_USE_ROLLER 1
#define CONFIG_LV_USE_SCALE 1
#define CONFIG_LV_USE_SLIDER 1
#define CONFIG_LV_USE_SPAN 1
#define CONFIG_LV_SPAN_SNIPPET_STACK_SIZE 64
#define CONFIG_LV_USE_SPINBOX 1
#define CONFIG_LV_USE_SPINNER 1
#define CONFIG_LV_USE_SWITCH 1
#define CONFIG_LV_USE_TEXTAREA 1
#define CONFIG_LV_TEXTAREA_DEF_PWD_SHOW_TIME 1500
#define CONFIG_LV_USE_TABLE 1
#define CONFIG_LV_USE_TABVIEW 1
#define CONFIG_LV_USE_TILEVIEW 1
#define CONFIG_LV_USE_WIN 1
#define CONFIG_LV_USE_THEME_DEFAULT 1
// #define CONFIG_LV_THEME_DEFAULT_DARK 0
#define CONFIG_LV_THEME_DEFAULT_GROW 1
#define CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME 80
#define CONFIG_LV_USE_THEME_SIMPLE 1
// #define CONFIG_LV_USE_THEME_MONO 0
#define CONFIG_LV_USE_FLEX 1
#define CONFIG_LV_USE_GRID 1
#define CONFIG_LV_FS_DEFAULT_DRIVE_LETTER 0
// #define CONFIG_LV_USE_FS_STDIO 0
// #define CONFIG_LV_USE_FS_POSIX 0
// #define CONFIG_LV_USE_FS_WIN32 0
// #define CONFIG_LV_USE_FS_FATFS 0
// #define CONFIG_LV_USE_FS_RAWFS 0
// #define CONFIG_LV_USE_FS_MEMFS 0
// #define CONFIG_LV_USE_FS_LITTLEFS 0
// #define CONFIG_LV_USE_FS_ARDUINO_ESP_LITTLEFS 0
// #define CONFIG_LV_USE_FS_ARDUINO_SD 0
// #define CONFIG_LV_USE_LODEPNG 0
// #define CONFIG_LV_USE_LIBPNG 0
// #define CONFIG_LV_USE_BMP 0
// #define CONFIG_LV_USE_TJPGD 0
// #define CONFIG_LV_USE_LIBJPEG_TURBO 0
// #define CONFIG_LV_USE_GIF 0
// #define CONFIG_LV_BIN_DECODER_RAM_LOAD 0
// #define CONFIG_LV_USE_RLE 0
// #define CONFIG_LV_USE_QRCODE 0
// #define CONFIG_LV_USE_BARCODE 0
// #define CONFIG_LV_USE_FREETYPE 0
// #define CONFIG_LV_USE_TINY_TTF 0
// #define CONFIG_LV_USE_RLOTTIE 0
// #define CONFIG_LV_USE_THORVG 0
// #define CONFIG_LV_USE_LZ4 0
// #define CONFIG_LV_USE_FFMPEG 0
// #define CONFIG_LV_USE_SNAPSHOT 0
#define CONFIG_LV_USE_SYSMON 1
#define CONFIG_LV_USE_PERF_MONITOR 1
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_LEFT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_RIGHT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_LEFT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_MID 0
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT 1
// #define CONFIG_LV_PERF_MONITOR_ALIGN_LEFT_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_RIGHT_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_CENTER 0
// #define CONFIG_LV_USE_PERF_MONITOR_LOG_MODE 0
// #define CONFIG_LV_USE_MEM_MONITOR 0
// #define CONFIG_LV_USE_PROFILER 0
// #define CONFIG_LV_USE_MONKEY 0
// #define CONFIG_LV_USE_GRIDNAV 0
// #define CONFIG_LV_USE_FRAGMENT 0
// #define CONFIG_LV_USE_IMGFONT 0
#define CONFIG_LV_USE_OBSERVER 1
// #define CONFIG_LV_USE_IME_PINYIN 0
// #define CONFIG_LV_USE_FILE_EXPLORER 0
#define CONFIG_LVGL_VERSION_MAJOR 9
#define CONFIG_LVGL_VERSION_MINOR 2
#define CONFIG_LVGL_VERSION_PATCH 1
// #define CONFIG_LV_USE_SDL 0
// #define CONFIG_LV_USE_X11 0
// #define CONFIG_LV_USE_WAYLAND 0
// #define CONFIG_LV_USE_LINUX_FBDEV 0
// #define CONFIG_LV_USE_NUTTX 0
// #define CONFIG_LV_USE_LINUX_DRM 0
// #define CONFIG_LV_USE_TFT_ESPI 0
// #define CONFIG_LV_USE_EVDEV 0
// #define CONFIG_LV_USE_LIBINPUT 0
// #define CONFIG_LV_USE_ST7735 0
// #define CONFIG_LV_USE_ST7789 0
// #define CONFIG_LV_USE_ST7796 0
// #define CONFIG_LV_USE_ILI9341 0
// #define CONFIG_LV_USE_GENERIC_MIPI 0
// #define CONFIG_LV_USE_RENESAS_GLCDC 0
// #define CONFIG_LV_USE_OPENGLES 0
// #define CONFIG_LV_USE_QNX 0
#define CONFIG_LV_BUILD_EXAMPLES 1
// #define CONFIG_LV_USE_DEMO_WIDGETS 0
// #define CONFIG_LV_USE_DEMO_KEYPAD_AND_ENCODER 0
// #define CONFIG_LV_USE_DEMO_RENDER 0
// #define CONFIG_LV_USE_DEMO_SCROLL 0
// #define CONFIG_LV_USE_DEMO_STRESS 0
// #define CONFIG_LV_USE_DEMO_MUSIC 0
// #define CONFIG_LV_USE_DEMO_FLEX_LAYOUT 0
// #define CONFIG_LV_USE_DEMO_MULTILANG 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
#define CONFIG_LV_SYSMON_GET_IDLE getIdleTaskPct
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0
#define CONFIG_FREERTOS_USE_CUSTOM_CONFIG_FRAGMENT 1
// #define MPU_SUPPORT 0
// #define USE_PERCEPIO_TRACELYZER 0

#endif /* _MCUX_CONFIG_H_ */
