# Copyright (c) 2014-2016, Freescale Semiconductor, Inc.
# Copyright 2016 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

#
# Generated by erpcgen 1.14.0 on Wed May 28 10:34:53 2025.
#
# AUTOGENERATED - DO NOT EDIT
#


