/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MK02FN64xxx10
package_id: MK02FN64VFM10
mcu_data: ksdk2_0
processor_version: 9.0.0
pin_labels:
- {pin_num: '20', pin_signal: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, label: M3_STEP, identifier: Lane0;M3_STEP}
- {pin_num: '23', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1, label: LED}
- {pin_num: '3', pin_signal: ADC0_SE4a/ADC0_DP1/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3, label: M0_STEP, identifier: M0_STEP}
- {pin_num: '4', pin_signal: ADC0_SE5a/ADC0_DM1/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3, label: M0_DIR, identifier: M0_DIR}
- {pin_num: '5', pin_signal: ADC0_SE6a/ADC0_DP2/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA, label: M1_DIR, identifier: M1_DIR}
- {pin_num: '6', pin_signal: ADC0_SE7a/ADC0_DM2/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL, label: M1_STEP, identifier: M1_STEP}
- {pin_num: '22', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0, label: RS_485_EN, identifier: RS_485_EN}
- {pin_num: '24', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT, label: RS_485_RX, identifier: RS_485_RX}
- {pin_num: '25', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT, label: RS_485_TX, identifier: RS_485_TX}
- {pin_num: '10', pin_signal: ADC0_SE17/PTE24/I2C0_SCL/EWM_OUT_b, label: MAG_M0}
- {pin_num: '11', pin_signal: ADC0_SE18/PTE25/I2C0_SDA/EWM_IN, label: MAG_M1}
- {pin_num: '18', pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, label: MOT_RESET, identifier: MOT_RESET}
- {pin_num: '17', pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, label: MOT_EN, identifier: MOT_EN}
- {pin_num: '21', pin_signal: ADC0_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, label: M3_DIR, identifier: M3_DIR}
- {pin_num: '26', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2, label: Lane1, identifier: Lane1}
- {pin_num: '27', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG, label: Lane0, identifier: Lane0}
- {pin_num: '29', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN, label: M2_STEP, identifier: M2_STEP}
- {pin_num: '30', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/EWM_OUT_b, label: M2_DIR, identifier: M2_DIR}
- {pin_num: '31', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM0_FLT0, label: MAG_M2, identifier: MAG_M2}
- {pin_num: '32', pin_signal: PTD7/UART0_TX/FTM0_CH1/FTM0_FLT1, label: MAG_M3, identifier: MAG_M3}
- {pin_num: '13', pin_signal: PTA1/UART0_RX/JTAG_TDI, label: MAG_M0, identifier: MAG_M0}
- {pin_num: '14', pin_signal: PTA2/UART0_TX/JTAG_TDO/TRACE_SWO, label: MAG_M1, identifier: MAG_M1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '23', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1}
  - {pin_num: '22', peripheral: UART1, signal: RTS, pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0, pull_select: up, pull_enable: enable}
  - {pin_num: '24', peripheral: UART1, signal: RX, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT, pull_select: up, pull_enable: enable}
  - {pin_num: '25', peripheral: UART1, signal: TX, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '18', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, direction: OUTPUT}
  - {pin_num: '17', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '20', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, identifier: M3_STEP, direction: OUTPUT}
  - {pin_num: '21', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, direction: OUTPUT}
  - {pin_num: '26', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2, direction: OUTPUT}
  - {pin_num: '27', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG, direction: OUTPUT}
  - {pin_num: '29', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/EWM_IN, direction: OUTPUT}
  - {pin_num: '30', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/EWM_OUT_b, direction: OUTPUT}
  - {pin_num: '31', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM0_FLT0, direction: INPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '32', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/UART0_TX/FTM0_CH1/FTM0_FLT1, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '3', peripheral: GPIOE, signal: 'GPIO, 16', pin_signal: ADC0_SE4a/ADC0_DP1/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOE, signal: 'GPIO, 17', pin_signal: ADC0_SE5a/ADC0_DM1/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3, direction: OUTPUT}
  - {pin_num: '5', peripheral: GPIOE, signal: 'GPIO, 18', pin_signal: ADC0_SE6a/ADC0_DP2/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA, direction: OUTPUT}
  - {pin_num: '6', peripheral: GPIOE, signal: 'GPIO, 19', pin_signal: ADC0_SE7a/ADC0_DM2/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/UART0_RX/JTAG_TDI, direction: INPUT}
  - {pin_num: '14', peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: PTA2/UART0_TX/JTAG_TDO/TRACE_SWO, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t MAG_M0_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 13)  */
    GPIO_PinInit(BOARD_INITPINS_MAG_M0_GPIO, BOARD_INITPINS_MAG_M0_PIN, &MAG_M0_config);

    gpio_pin_config_t MAG_M1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA2 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_MAG_M1_GPIO, BOARD_INITPINS_MAG_M1_PIN, &MAG_M1_config);

    gpio_pin_config_t MOT_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA18 (pin 17)  */
    GPIO_PinInit(BOARD_INITPINS_MOT_EN_GPIO, BOARD_INITPINS_MOT_EN_PIN, &MOT_EN_config);

    gpio_pin_config_t MOT_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA19 (pin 18)  */
    GPIO_PinInit(BOARD_INITPINS_MOT_RESET_GPIO, BOARD_INITPINS_MOT_RESET_PIN, &MOT_RESET_config);

    gpio_pin_config_t M3_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 20)  */
    GPIO_PinInit(BOARD_INITPINS_M3_STEP_GPIO, BOARD_INITPINS_M3_STEP_PIN, &M3_STEP_config);

    gpio_pin_config_t M3_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 21)  */
    GPIO_PinInit(BOARD_INITPINS_M3_DIR_GPIO, BOARD_INITPINS_M3_DIR_PIN, &M3_DIR_config);

    gpio_pin_config_t Lane1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 26)  */
    GPIO_PinInit(BOARD_INITPINS_Lane1_GPIO, BOARD_INITPINS_Lane1_PIN, &Lane1_config);

    gpio_pin_config_t Lane0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 27)  */
    GPIO_PinInit(BOARD_INITPINS_Lane0_GPIO, BOARD_INITPINS_Lane0_PIN, &Lane0_config);

    gpio_pin_config_t M2_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_M2_STEP_GPIO, BOARD_INITPINS_M2_STEP_PIN, &M2_STEP_config);

    gpio_pin_config_t M2_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 30)  */
    GPIO_PinInit(BOARD_INITPINS_M2_DIR_GPIO, BOARD_INITPINS_M2_DIR_PIN, &M2_DIR_config);

    gpio_pin_config_t MAG_M2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_MAG_M2_GPIO, BOARD_INITPINS_MAG_M2_PIN, &MAG_M2_config);

    gpio_pin_config_t MAG_M3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 32)  */
    GPIO_PinInit(BOARD_INITPINS_MAG_M3_GPIO, BOARD_INITPINS_MAG_M3_PIN, &MAG_M3_config);

    gpio_pin_config_t M0_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE16 (pin 3)  */
    GPIO_PinInit(BOARD_INITPINS_M0_STEP_GPIO, BOARD_INITPINS_M0_STEP_PIN, &M0_STEP_config);

    gpio_pin_config_t M0_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE17 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_M0_DIR_GPIO, BOARD_INITPINS_M0_DIR_PIN, &M0_DIR_config);

    gpio_pin_config_t M1_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE18 (pin 5)  */
    GPIO_PinInit(BOARD_INITPINS_M1_DIR_GPIO, BOARD_INITPINS_M1_DIR_PIN, &M1_DIR_config);

    gpio_pin_config_t M1_STEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE19 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_M1_STEP_GPIO, BOARD_INITPINS_M1_STEP_PIN, &M1_STEP_config);

    /* PORTA1 (pin 13) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_MAG_M0_PORT, BOARD_INITPINS_MAG_M0_PIN, kPORT_MuxAsGpio);

    /* PORTA18 (pin 17) is configured as PTA18 */
    PORT_SetPinMux(BOARD_INITPINS_MOT_EN_PORT, BOARD_INITPINS_MOT_EN_PIN, kPORT_MuxAsGpio);

    /* PORTA19 (pin 18) is configured as PTA19 */
    PORT_SetPinMux(BOARD_INITPINS_MOT_RESET_PORT, BOARD_INITPINS_MOT_RESET_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 14) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_MAG_M1_PORT, BOARD_INITPINS_MAG_M1_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 20) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_M3_STEP_PORT, BOARD_INITPINS_M3_STEP_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 21) is configured as PTB1 */
    PORT_SetPinMux(BOARD_INITPINS_M3_DIR_PORT, BOARD_INITPINS_M3_DIR_PIN, kPORT_MuxAsGpio);

    /* PORTC1 (pin 22) is configured as UART1_RTS_b */
    PORT_SetPinMux(BOARD_INITPINS_RS_485_EN_PORT, BOARD_INITPINS_RS_485_EN_PIN, kPORT_MuxAlt3);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC2 (pin 23) is configured as PTC2 */
    PORT_SetPinMux(PORTC, 2U, kPORT_MuxAsGpio);

    /* PORTC3 (pin 24) is configured as UART1_RX */
    PORT_SetPinMux(BOARD_INITPINS_RS_485_RX_PORT, BOARD_INITPINS_RS_485_RX_PIN, kPORT_MuxAlt3);

    PORTC->PCR[3] = ((PORTC->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC4 (pin 25) is configured as UART1_TX */
    PORT_SetPinMux(BOARD_INITPINS_RS_485_TX_PORT, BOARD_INITPINS_RS_485_TX_PIN, kPORT_MuxAlt3);

    PORTC->PCR[4] = ((PORTC->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC5 (pin 26) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_Lane1_PORT, BOARD_INITPINS_Lane1_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 27) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_Lane0_PORT, BOARD_INITPINS_Lane0_PIN, kPORT_MuxAsGpio);

    /* PORTD4 (pin 29) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_M2_STEP_PORT, BOARD_INITPINS_M2_STEP_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 30) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_M2_DIR_PORT, BOARD_INITPINS_M2_DIR_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin 31) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_MAG_M2_PORT, BOARD_INITPINS_MAG_M2_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[6] = ((PORTD->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTD7 (pin 32) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_MAG_M3_PORT, BOARD_INITPINS_MAG_M3_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE16 (pin 3) is configured as PTE16 */
    PORT_SetPinMux(BOARD_INITPINS_M0_STEP_PORT, BOARD_INITPINS_M0_STEP_PIN, kPORT_MuxAsGpio);

    /* PORTE17 (pin 4) is configured as PTE17 */
    PORT_SetPinMux(BOARD_INITPINS_M0_DIR_PORT, BOARD_INITPINS_M0_DIR_PIN, kPORT_MuxAsGpio);

    /* PORTE18 (pin 5) is configured as PTE18 */
    PORT_SetPinMux(BOARD_INITPINS_M1_DIR_PORT, BOARD_INITPINS_M1_DIR_PIN, kPORT_MuxAsGpio);

    /* PORTE19 (pin 6) is configured as PTE19 */
    PORT_SetPinMux(BOARD_INITPINS_M1_STEP_PORT, BOARD_INITPINS_M1_STEP_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK)))

                  /* UART 1 transmit data source select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
