/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_EN 0x20u       /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_PULLUP 0x10u  /*!<@brief Selects pull-up function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_16 (number 15), RS485_RTS
  @{ */
#define BOARD_INITRS485_RS485_RTS_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITRS485_RS485_RTS_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITRS485_RS485_RTS_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO0_17 (number 48), RS485-TX
  @{ */
#define BOARD_INITRS485_RS485_TX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITRS485_RS485_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITRS485_RS485_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_18 (number 47), RS485_RX
  @{ */
#define BOARD_INITRS485_RS485_RX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITRS485_RS485_RX_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITRS485_RS485_RX_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitRS485(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCDC(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2cPins(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2cPinsAsGPIO(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
