/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _ERPC_CONFIG_GEN_H_
#define _ERPC_CONFIG_GEN_H_

#define CONFIG_ERPC_ALLOCATION_POLICY_DYNAMIC 1U
// #define CONFIG_ERPC_ALLOCATION_POLICY_STATIC 0U
#define ERPC_ALLOCATION_POLICY (ERPC_ALLOCATION_POLICY_DYNAMIC)
#define ERPC_CODEC_COUNT 2U
#define ERPC_MESSAGE_LOGGERS_COUNT 0U
#define ERPC_CLIENTS_THREADS_AMOUNT 1U
#define CONFIG_ERPC_THREADS_NONE 1U
// #define CONFIG_ERPC_THREADS_PTHREADS 0U
// #define CONFIG_ERPC_THREADS_FREERTOS 0U
// #define CONFIG_ERPC_THREADS_ZEPHYR 0U
// #define CONFIG_ERPC_THREADS_MBED 0U
// #define CONFIG_ERPC_THREADS_WIN32 0U
// #define CONFIG_ERPC_THREADS_THREADX 0U
#define ERPC_THREADS (ERPC_THREADS_NONE)
#define ERPC_DEFAULT_BUFFER_SIZE 256U
#define ERPC_DEFAULT_BUFFERS_COUNT 2U
// #define ERPC_NOEXCEPT 0U
// #define ERPC_NESTED_CALLS 0U
// #define ERPC_NESTED_CALLS_DETECTION 0U
// #define ERPC_MESSAGE_LOGGING 0U
// #define ERPC_TRANSPORT_MU_USE_MCMGR 0U
// #define ERPC_PRE_POST_ACTION 0U
// #define ERPC_PRE_POST_ACTION_DEFAULT 0U

#endif /* _ERPC_CONFIG_GEN_H_ */
