# Add set(CONFIG_USE_middleware_lvgl true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
          ${CMAKE_CURRENT_LIST_DIR}/src/lv_init.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_group.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_class.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_draw.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_event.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_id_builtin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_pos.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_property.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_scroll.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_style.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_style_gen.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_obj_tree.c
          ${CMAKE_CURRENT_LIST_DIR}/src/core/lv_refr.c
          ${CMAKE_CURRENT_LIST_DIR}/src/display/lv_display.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_arc.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_buf.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_image.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_label.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_line.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_mask.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_rect.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_triangle.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_draw_vector.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/lv_image_decoder.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_draw_buf_pxp.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_draw_pxp.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_draw_pxp_fill.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_draw_pxp_img.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_draw_pxp_layer.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_pxp_cfg.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_pxp_osa.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/pxp/lv_pxp_utils.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_buf_vglite.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_arc.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_border.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_fill.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_img.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_label.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_layer.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_line.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_draw_vglite_triangle.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_vglite_buf.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_vglite_matrix.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_vglite_path.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite/lv_vglite_utils.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sdl/lv_draw_sdl.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_al88.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_i1.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_l8.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_arc.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_border.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_box_shadow.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_fill.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_gradient.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_img.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_letter.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_line.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_mask.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_mask_rect.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_transform.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_triangle.c
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/sw/lv_draw_sw_vector.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/drm/lv_linux_drm.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/fb/lv_linux_fbdev.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/ili9341/lv_ili9341.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/lcd/lv_lcd_generic_mipi.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/st7735/lv_st7735.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/st7789/lv_st7789.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/display/st7796/lv_st7796.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/evdev/lv_evdev.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/libinput/lv_libinput.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/libinput/lv_xkb.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_cache.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_entry.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_fbdev.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_image_cache.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_lcd.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_libuv.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_profiler.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/nuttx/lv_nuttx_touchscreen.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/sdl/lv_sdl_keyboard.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/sdl/lv_sdl_mouse.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/sdl/lv_sdl_mousewheel.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/sdl/lv_sdl_window.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/windows/lv_windows_context.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/windows/lv_windows_display.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/windows/lv_windows_input.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/x11/lv_x11_display.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/x11/lv_x11_input.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/glfw/lv_glfw_window.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/glfw/lv_opengles_debug.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/glfw/lv_opengles_driver.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/glfw/lv_opengles_texture.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/qnx/lv_qnx.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/wayland/lv_wayland.c
          ${CMAKE_CURRENT_LIST_DIR}/src/drivers/wayland/lv_wayland_smm.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_binfont_loader.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_dejavu_16_persian_hebrew.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_fmt_txt.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_10.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_12.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_14.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_16.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_18.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_20.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_22.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_24.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_26.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_28.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_28_compressed.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_30.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_32.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_34.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_36.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_38.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_40.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_42.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_44.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_46.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_48.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_montserrat_8.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_simsun_14_cjk.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_simsun_16_cjk.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_unscii_16.c
          ${CMAKE_CURRENT_LIST_DIR}/src/font/lv_font_unscii_8.c
          ${CMAKE_CURRENT_LIST_DIR}/src/indev/lv_indev.c
          ${CMAKE_CURRENT_LIST_DIR}/src/indev/lv_indev_scroll.c
          ${CMAKE_CURRENT_LIST_DIR}/src/layouts/flex/lv_flex.c
          ${CMAKE_CURRENT_LIST_DIR}/src/layouts/grid/lv_grid.c
          ${CMAKE_CURRENT_LIST_DIR}/src/layouts/lv_layout.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/barcode/code128.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/barcode/lv_barcode.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/bin_decoder/lv_bin_decoder.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/bmp/lv_bmp.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/ffmpeg/lv_ffmpeg.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/freetype/lv_freetype.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/freetype/lv_freetype_glyph.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/freetype/lv_freetype_image.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/freetype/lv_freetype_outline.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/freetype/lv_ftsystem.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_cbfs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_fatfs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_littlefs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_memfs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_posix.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_rawfs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_stdio.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/fsdrv/lv_fs_win32.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/gif/gifdec.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/gif/lv_gif.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/libpng/lv_libpng.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/lodepng/lodepng.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/lodepng/lv_lodepng.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/lz4/lz4.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/qrcode/lv_qrcode.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/qrcode/qrcodegen.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/rle/lv_rle.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/rlottie/lv_rlottie.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/tiny_ttf/lv_tiny_ttf.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/tjpgd/lv_tjpgd.c
          ${CMAKE_CURRENT_LIST_DIR}/src/libs/tjpgd/tjpgd.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/cache/lv_cache.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/cache/lv_cache_entry.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/cache/lv_cache_lru_rb.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/cache/lv_image_cache.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/cache/lv_image_header_cache.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_anim.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_anim_timeline.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_area.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_array.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_async.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_bidi.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_color.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_color_op.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_event.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_fs.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_ll.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_log.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_lru.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_math.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_matrix.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_palette.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_profiler_builtin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_rb.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_style.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_style_gen.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_templ.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_text.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_text_ap.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_timer.c
          ${CMAKE_CURRENT_LIST_DIR}/src/misc/lv_utils.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_cmsis_rtos2.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_freertos.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_linux.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_mqx.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_os.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_os_none.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_pthread.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_rtthread.c
          ${CMAKE_CURRENT_LIST_DIR}/src/osal/lv_windows.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/file_explorer/lv_file_explorer.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/fragment/lv_fragment.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/fragment/lv_fragment_manager.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/gridnav/lv_gridnav.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/ime/lv_ime_pinyin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/imgfont/lv_imgfont.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/monkey/lv_monkey.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/observer/lv_observer.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/snapshot/lv_snapshot.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/sysmon/lv_sysmon.c
          ${CMAKE_CURRENT_LIST_DIR}/src/others/vg_lite_tvg/vg_lite_matrix.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/builtin/lv_mem_core_builtin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/builtin/lv_sprintf_builtin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/builtin/lv_string_builtin.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/builtin/lv_tlsf.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/clib/lv_mem_core_clib.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/clib/lv_sprintf_clib.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/clib/lv_string_clib.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/lv_mem.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/micropython/lv_mem_core_micropython.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/rtthread/lv_mem_core_rtthread.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/rtthread/lv_sprintf_rtthread.c
          ${CMAKE_CURRENT_LIST_DIR}/src/stdlib/rtthread/lv_string_rtthread.c
          ${CMAKE_CURRENT_LIST_DIR}/src/themes/default/lv_theme_default.c
          ${CMAKE_CURRENT_LIST_DIR}/src/themes/lv_theme.c
          ${CMAKE_CURRENT_LIST_DIR}/src/themes/mono/lv_theme_mono.c
          ${CMAKE_CURRENT_LIST_DIR}/src/themes/simple/lv_theme_simple.c
          ${CMAKE_CURRENT_LIST_DIR}/src/tick/lv_tick.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/animimage/lv_animimage.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/arc/lv_arc.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/bar/lv_bar.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/button/lv_button.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/buttonmatrix/lv_buttonmatrix.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/calendar/lv_calendar.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/calendar/lv_calendar_chinese.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/calendar/lv_calendar_header_arrow.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/calendar/lv_calendar_header_dropdown.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/carousel/lv_carousel.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/canvas/lv_canvas.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/chart/lv_chart.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/checkbox/lv_checkbox.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/dropdown/lv_dropdown.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/image/lv_image.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/imagebutton/lv_imagebutton.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/keyboard/lv_keyboard.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/label/lv_label.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/led/lv_led.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/line/lv_line.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/list/lv_list.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/lottie/lv_lottie.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/menu/lv_menu.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/msgbox/lv_msgbox.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/objx_templ/lv_objx_templ.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/roller/lv_roller.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/scale/lv_scale.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/slider/lv_slider.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/span/lv_span.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/spinbox/lv_spinbox.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/spinner/lv_spinner.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/switch/lv_switch.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/table/lv_table.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/tabview/lv_tabview.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/textarea/lv_textarea.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/tileview/lv_tileview.c
          ${CMAKE_CURRENT_LIST_DIR}/src/widgets/win/lv_win.c
        )

  
      target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/.
          ${CMAKE_CURRENT_LIST_DIR}/src/draw/nxp/vglite
        )

    if(CONFIG_USE_COMPONENT_CONFIGURATION)
  message("===>Import configuration from ${CMAKE_CURRENT_LIST_FILE}")

      target_compile_definitions(${MCUX_SDK_PROJECT_NAME} PUBLIC
                  -DLV_CONF_INCLUDE_SIMPLE=1
              )
  
            if(CONFIG_TOOLCHAIN STREQUAL mcux)
      target_compile_options(${MCUX_SDK_PROJECT_NAME} PUBLIC
              -Wno-format
              -fms-extensions
            )
      endif()
          if(CONFIG_TOOLCHAIN STREQUAL armgcc)
      target_compile_options(${MCUX_SDK_PROJECT_NAME} PUBLIC
              -fms-extensions
            )
      endif()
          if(CONFIG_TOOLCHAIN STREQUAL mdk)
      target_compile_options(${MCUX_SDK_PROJECT_NAME} PUBLIC
              -fms-extensions
            )
      endif()
      
  endif()

