/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC1 (number 22), RS_485_EN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS_485_EN_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS_485_EN_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS_485_EN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC3 (number 24), RS_485_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS_485_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS_485_RX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS_485_RX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC4 (number 25), RS_485_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS_485_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS_485_TX_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS_485_TX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA19 (number 18), MOT_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOT_RESET_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOT_RESET_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT_RESET_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT_RESET_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT_RESET_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTA18 (number 17), MOT_EN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOT_EN_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOT_EN_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT_EN_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT_EN_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT_EN_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB0 (number 20), M3_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M3_STEP_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M3_STEP_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M3_STEP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M3_STEP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M3_STEP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB1 (number 21), M3_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M3_DIR_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M3_DIR_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M3_DIR_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M3_DIR_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M3_DIR_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC5 (number 26), Lane1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Lane1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Lane1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Lane1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Lane1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Lane1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC6 (number 27), Lane0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Lane0_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Lane0_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Lane0_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Lane0_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Lane0_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD4 (number 29), M2_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M2_STEP_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M2_STEP_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M2_STEP_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M2_STEP_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M2_STEP_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTD5 (number 30), M2_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M2_DIR_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M2_DIR_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M2_DIR_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M2_DIR_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M2_DIR_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD6 (number 31), MAG_M2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAG_M2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MAG_M2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MAG_M2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MAG_M2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MAG_M2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD7 (number 32), MAG_M3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAG_M3_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MAG_M3_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MAG_M3_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MAG_M3_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MAG_M3_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE16 (number 3), M0_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M0_STEP_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M0_STEP_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M0_STEP_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M0_STEP_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M0_STEP_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE17 (number 4), M0_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M0_DIR_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M0_DIR_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M0_DIR_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M0_DIR_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M0_DIR_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTE18 (number 5), M1_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M1_DIR_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M1_DIR_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M1_DIR_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M1_DIR_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M1_DIR_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTE19 (number 6), M1_STEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_M1_STEP_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_M1_STEP_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_M1_STEP_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_M1_STEP_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_M1_STEP_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA1 (number 13), MAG_M0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAG_M0_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MAG_M0_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MAG_M0_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MAG_M0_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MAG_M0_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA2 (number 14), MAG_M1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MAG_M1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MAG_M1_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MAG_M1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MAG_M1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MAG_M1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
