/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _USB_DEVICE_CONFIG_H_
#define _USB_DEVICE_CONFIG_H_

#define USB_DEVICE_CONFIG_KHCI 1
#define USB_DEVICE_CONFIG_KHCI_DMA_ALIGN_BUFFER_LENGTH 64
#define USB_DEVICE_CONFIG_EHCI 0
#define USB_DEVICE_CONFIG_EHCI_MAX_DTD 16
#define USB_DEVICE_CONFIG_LPCIP3511FS 0
#define USB_DEVICE_CONFIG_LPCIP3511HS 0
#define USB_DEVICE_CONFIG_NUM (USB_DEVICE_CONFIG_KHCI + USB_DEVICE_CONFIG_EHCI + USB_DEVICE_CONFIG_LPCIP3511FS + USB_DEVICE_CONFIG_LPCIP3511HS)
#define USB_DEVICE_CONFIG_AUDIO 1
#define USB_DEVICE_CONFIG_AUDIO_CLASS_2_0 1
#define USB_DEVICE_CONFIG_CDC_ACM 0
#define USB_DEVICE_CONFIG_CDC_ECM 0
#define USB_DEVICE_CONFIG_CDC_RNDIS 0
#define USB_DEVICE_CONFIG_HID 0
#define USB_DEVICE_CONFIG_PRINTER 0
#define USB_DEVICE_CONFIG_MSC 0
#define USB_DEVICE_CONFIG_CCID 0
#define USB_DEVICE_CONFIG_VIDEO 0
#define USB_DEVICE_CONFIG_PHDC 0
#define USB_DEVICE_CONFIG_DFU 0
#define USB_DEVICE_CONFIG_MTP 0
#define USB_DEVICE_CONFIG_SELF_POWER 1
#define USB_DEVICE_CONFIG_ENDPOINTS 4
// #define USB_DEVICE_CONFIG_GET_SOF_COUNT 0
// #define USB_DEVICE_CONFIG_SOF_NOTIFICATIONS 0
// #define USB_DEVICE_CONFIG_ERROR_HANDLING 0
// #define USB_DEVICE_CONFIG_RETURN_VALUE_CHECK 0
// #define USB_DEVICE_CONFIG_USE_TASK 0
#define USB_DEVICE_CONFIG_MAX_MESSAGES 8
// #define USB_DEVICE_CONFIG_DETACH_ENABLE 0
// #define USB_DEVICE_CONFIG_CDC_CIC_EP_DISABLE 0
// #define USB_DEVICE_CONFIG_LOW_POWER_MODE 0
// #define USB_DEVICE_CONFIG_REMOTE_WAKEUP 0
#define USB_DEVICE_CONFIG_ROOT2_TEST 1
// #define USB_DEVICE_CONFIG_KEEP_ALIVE_MODE 0
// #define USB_DEVICE_CONFIG_USB20_TEST_MODE 0
// #define USB_DEVICE_CONFIG_CV_TEST 0
// #define USB_DEVICE_CONFIG_COMPLIANCE_TEST 0

#endif /* _USB_DEVICE_CONFIG_H_ */
